export const FETCH_MVPS_START = "FETCH_MVPS_START";
export const FETCH_MVPS_FAIL = "FETCH_MVPS_FAIL";
export const FETCH_MVPS_SUCCESS = "FETCH_MVPS_SUCCESS";
export const FETCH_MVPS_LOCAL = "FETCH_MVPS_LOCAL";