export const FETCH_MVPS_START = "FETCH_MVPS_START";
export const FETCH_MVPS_FAIL = "FETCH_MVPS_FAIL";
export const FETCH_MVPS_SUCCESS = "FETCH_MVPS_SUCCESS";

export const SAVE_MVPS_START = "SAVE_MVPS_START";
export const SAVE_MVPS_FAIL = "SAVE_MVPS_FAIL";
export const SAVE_MVPS_SUCCESS = "SAVE_MVPS_SUCCESS";

export const FETCH_MVPS_LOCAL = "FETCH_MVPS_LOCAL";
export const SAVE_MVPS_LOCAL = "SAVE_MVPS_LOCAL";

export const UPDATE_CURRENT_TIME = "UPDATE_CURRENT_TIME";
export const MVP_KILLED = "MVP_KILLED";
export const CALCULATE_TIME_TILL_SPAWN = "CALCULATE_TIME_TILL_SPAWN";

export const CREATE_MVPS_SUCCESS = "CREATE_MVPS_SUCCESS";
export const CREATE_MVPS_FAIL = "CREATE_MVPS_FAIL";
export const CREATE_MVPS_START = "CREATE_MVPS_START";


// export const SET_TRACKER_NAMES = "SET_TRACKER_NAMES";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_INITIATE_LOGOUT = "AUTH_INITIATE_LOGOUT";
export const AUTH_LOGOUT = "AUTH_LOGOUT";